# Generated by Django 5.2.8 on 2025-11-08 11:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('typical_gear_categories', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GearCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('typical_weight_grams', models.IntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='catalog_photos/')),
                ('common_activities', models.JSONField(blank=True, default=list)),
                ('weather_conditions', models.JSONField(blank=True, default=list)),
                ('popularity_score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.category')),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.IntegerField(editable=False)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('expected_temp_min', models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('expected_temp_max', models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('expected_weather', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gear_photos/')),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gear.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('recommended', 'Recommended'), ('user_added', 'User Added')], default='recommended', max_length=20)),
                ('packed', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('usefulness_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to='gear.trip')),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_usages', to='gear.usergear')),
            ],
        ),
        migrations.CreateModel(
            name='GearUsageStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_packed', models.IntegerField(default=0)),
                ('times_used', models.IntegerField(default=0)),
                ('times_not_used', models.IntegerField(default=0)),
                ('avg_usefulness_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('usage_by_activity', models.JSONField(blank=True, default=dict)),
                ('usage_by_weather', models.JSONField(blank=True, default=dict)),
                ('usage_by_duration', models.JSONField(blank=True, default=dict)),
                ('last_used_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.usergear')),
            ],
            options={
                'verbose_name_plural': 'Gear usage statistics',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'status'], name='gear_trip_user_id_8e4474_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'start_date'], name='gear_trip_user_id_b39080_idx'),
        ),
        migrations.AddIndex(
            model_name='usergear',
            index=models.Index(fields=['user', 'category'], name='gear_userge_user_id_315722_idx'),
        ),
        migrations.AddIndex(
            model_name='tripgear',
            index=models.Index(fields=['trip', 'packed'], name='gear_tripge_trip_id_c17018_idx'),
        ),
        migrations.AddIndex(
            model_name='tripgear',
            index=models.Index(fields=['trip', 'used'], name='gear_tripge_trip_id_5dd98b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tripgear',
            unique_together={('trip', 'gear')},
        ),
        migrations.AlterUniqueTogether(
            name='gearusagestats',
            unique_together={('user', 'gear')},
        ),
    ]
