# Generated by Django 5.2.8 on 2025-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gearusagestats',
            name='usage_by_activity',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gearusagestats',
            name='usage_by_duration',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='gearusagestats',
            name='usage_by_weather',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
