# Generated by Django 5.2.8 on 2025-12-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_alter_gearusagestats_usage_by_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='expected_weather',
            field=models.JSONField(blank=True, default=list, help_text='List of weather conditions'),
        ),
    ]
